Vagrant.configure("2") do |vm01|
   vm01.vm.box = "generic/ubuntu2210"   
   vm01.vm.network "forwarded_port", guest: 80, host: 8080
   vm01.vm.network "private_network", ip: "192.168.56.10"
   vm01.vm.synced_folder "./data", "/vagrant_data"  

   vm01.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = "2048"
   end

  vm01.vm.provision "shell" , inline: <<-SHELL
    dhclient eth0
    apt-get update
    apt-get install apache2 -y
  SHELL

end
